### ISSUE TITLE
PDF preview doesn't work in Safari (latest version)

### ISSUE THREAD

**Issue by TwoMoreThings** [dampee/ImageProcessor.Plugins.Pdf#11]
I don't have Safari, but on a screenshare saw all images showing as broken images, e.g. on this page which works in Chrome, Firefox, and Edge

http://heritage.bcsoccer.localhost/heritage-archive/historical-documents/

many thanks
t

**Comment by TwoMoreThings** [comment]
In my defence it was late! It turns out I had mode=pdf, instead of format=pdf,

Interesting that Chrome and Firefox displayed an image for the PDFs (but only mildly interesting)

Now where's the option for me to delete an issue??
regards
t

**Comment by dampee** [comment]
Only admins from the project can delete an issue.

should we keep the issue so that people can find the answer if they have the same issue on a late evening?

I think we should.
