### ISSUE TITLE
NuGet Update

### ISSUE THREAD

**Issue by geoffappleford** [dampee/ImageProcessor.Plugins.Pdf#8]
@dampee, any chance you can update the NuGet release. The "Use in memory version (#7)" commit is essential for this plugin and that's not in the current (1.2.0) NuGet package.

It's not hard to compile the source myself but it would be nice to be able to just include the NuGet package.

Otherwise, great work and thank you.

Geoff

**Comment by dampee** [comment]
Thanks for the notification! Update is on its way!

https://www.nuget.org/packages/ImageProcessor.Plugins.PDF/1.3.0
